<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudentPoll</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class="container body-content">
        <h1>Admin</h1>
<?php

        $con = mysqli_connect("localhost", "root", "", "studentpoll");
        $res = mysqli_query($con, "SELECT * FROM TutorGroups");
        $first = -1;

?>
        <div class="col-md-6">
            <input type="password" id="token" placeholder="security token" />
        </div>
        <div class="col-md-6">
        <form>
            <select id="group">
<?php
                while($group = mysqli_fetch_assoc($res)) { if($first < 0) $first = $group['Id'];
                    ?>              <option value="<?=$group['Id']?>"><?=$group['Name']?></option>
<?php } ?>
            </select>
        </form>
        </div>

        <div class="polls">
<?php
            mysqli_free_result($res);
            $res = mysqli_query($con, "SELECT * FROM Polls");
            while($poll = mysqli_fetch_assoc($res))
            {?>
            <div class="poll<?=($poll['Id'] == $first ? "" : ' hidden')?>" data-pollid="<?=$poll['Id']?>">
                    <div class="col-md-6"><?=$poll['Title']?></div>
                    <div class="col-md-2"><button class="btn btn-primary" data-role="abutton" data-pollid="<?=$poll['Id']?>">Aktivieren</button></div>
                    <div class="col-md-2"><button class="btn btn-primary" data-role="dbutton" data-pollid="<?=$poll['Id']?>">Anzeigen</button></div>
                    <div class="col-md-2"><button class="btn btn-primary" data-role="ebutton" data-pollid="<?=$poll['Id']?>">Ergebnisse</button></div>
                </div>
<?php  } mysqli_free_result($res);
?>
        </div>

        <hr />
        <footer>
            <p>Made with ❤. Grab it from <a href="https://github.com/mistressofjellyfish/studentpoll">GitHub</a>.</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/jquery.signalR-2.2.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="http://<?=$_SERVER['SERVER_NAME']?>:1337/signalr/hubs"></script>
    <script type="text/javascript">
        $(function () {
            $.connection.hub.url = "http://<?=$_SERVER['SERVER_NAME']?>:1337/signalr";
            var poll = $.connection.pollHub;

            $('#group').change(function(e) {
                // hide everything
                $('.poll').not('.hidden').addClass('hidden');
                // show what we want
                $(".poll[data-pollid='"+this.value+"']").removeClass('hidden');
            });

            $("[data-role='abutton']").click(function (e) {
                poll.server.activate($(this).data("pollid"), $("#token").val());
            });
            $("[data-role='dbutton']").click(function (e) {
                poll.server.display($(this).data("pollid"), $("#token").val());
            });
            $("[data-role='ebutton']").click(function (e) {
                poll.server.results($(this).data("pollid"), $("#token").val());
            });

            poll.client.display = function (poll) {

            };

            poll.client.activatePoll = function (poll) {

            };

            poll.client.showResult = function (result) {

            };

            poll.client.voteOk = function () {

            }
            $.connection.hub.logging = true;
            $.connection.hub.start();
        });
    </script>
</body>
</html>

<!-- vim:set et:-->
