<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudentPoll</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class="container body-content">
        <div id="buttonframe">
            <h1 data-template="question"></h1>
            <div id="buttons" style="font-size: 18px">
                <div data-role="button-template" class="hidden">
                    <div class="col-md-10" data-template="text" style="margin-bottom:20px;"></div>
                </div>
            </div>
        </div>
        <h1 data-template="resultTitle"></h1>
        <div style="width:600px;">
        <canvas id="myChart" width="600" height="600"></canvas>
        </div>
        <hr />
        <footer>
            <p>Made with ❤. Soon on GitHub.</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/jquery.signalR-2.2.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="http://<?=$_SERVER['SERVER_NAME']?>:1337/signalr/hubs"></script>
    <script type="text/javascript" src="/Chart.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $.connection.hub.url = "http://<?=$_SERVER['SERVER_NAME']?>:1337/signalr";

            var poll = $.connection.pollHub;
            var $template = $("[data-role='button-template']").clone();
            var chart = null;
            $("#mychart").hide();

            poll.client.activatePoll = function (poll) {
                $("#buttons").empty();
                $("#mychart").hide();
                $("[data-template='resultTitle']").text("");
                $("[data-template='question']").text(poll.Title);

                for (var i = 0; i < poll.Answers.length; i++) {
                    $t = $template.clone();
                    $t.find("[data-template='text']").text("Antwort " + i + ": " + poll.Answers[i].Text);
                    $t.removeClass("hidden");
                    $("#buttons").append($t);
                }
                $("#buttonframe").show();
            };

            poll.client.display = function (poll) {
                $("#mychart").hide();
                $("#buttons").empty();
                $("[data-template='resultTitle']").text("");
                $("[data-template='question']").text(poll.Title);

                for (var i = 0; i < poll.Answers.length; i++) {
                    $t = $template.clone();
                    $t.find("[data-template='text']").text("Antwort " + i + ": " + poll.Answers[i].Text);
                    $t.removeClass("hidden");
                    $("#buttons").append($t);
                }
                $("#buttonframe").show();
            };

            poll.client.showResult = function (result, title) {
                $("#buttonframe").hide();
                $("[data-template='resultTitle']").text(title);

                chart = new Chart($("#myChart"), {
                    type: 'bar',
                    data: result,
                    options: {}
                    });

                $("#myChart").show();
            };

            poll.client.voteOk = function () {

            };
$.connection.hub.logging = true;
            $.connection.hub.start();
        });
    </script>
</body>
</html>
